stages:
  - package
  - collect
  - upload

include:
  - project: 'DRS/linux-packages/shared-ci-pipeline'
    file: '.upload_rhel-gitlab-ci.yml'
  - project: 'DRS/linux-packages/templated-python-venv/shared-pipelines'
    file: '.el-venv-gitlab-ci.yml'

variables:
  PKG_PREFIX: 'liuopt'
  PKG_VERSION: '1'
  PKG_RELEASE: '1'

.ccc-rhel-opt-package:
  stage: package
  when: manual
  variables:
    PKG_NAME: 'liuopt-cccollector'
    PKG_INSTALLPATH: '/opt/liu'
    PKG_PROG_VER: '1'
  artifacts:
    paths:
      - pkgs
  script:
    - dnf update
    - rpmbuild collector.spec
    - mkdir -p pkgs/rhel${dist_ver}
    - mv rpms/noarch/*.rpm pkgs/rhel${dist_ver}
    #           ^ Elsewhere?

ccc-rhel8-opt-package:
  extends: .ccc-rhel-opt-package
  image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel8:latest'
  variables:
    dist_ver: 8

ccc-rhel9-opt-package:
  extends: .ccc-rhel-opt-package
  image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel9:latest'
  variables:
    dist_ver: 9

pywb-rhel-opt-package:
  extends: .el-venv-opt-package
  when: manual
  variables:
    PKG_NAME: 'liuopt-ccc-pywb-venv'
    PKG_INSTALLPATH: 'opt/liu'
    PKG_PROG_VER: '1-1'

pywb-rhel8-opt-package:
  extends: .pywb-rhel-opt-package:
  variables:
    target_distro: rhel8
    build_image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel8:latest'

pywb-rhel9-opt-package:
  extends: .pywb-rhel-opt-package:
  variables:
    target_distro: rhel9
    build_image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel9:latest'

collect-pkgs:
  stage: collect
  when: manual
  artifacts:
    untracked: true
  dependencies:
    - ccc-rhel-opt-package
    - pywb-rhel-opt-package
  script:
    - "mv pkgs/* ."
    - "find . | grep .rpm"

upload-rhel8-pkgs:
  extends: .upload-el-pkgs
  dependencies:
    - collect-pkgs
  variables:
    target_dir: rhel8
    upload_script: './upload-Ootpa-test.sh'

upload-rhel9-pkgs:
  extends: .upload-el-pkgs
  dependencies:
    - collect-pkgs
  variables:
    target_dir: rhel9
    upload_script: './upload-Plow-test.sh'
