stages:
  - package
  - collect
  - upload

include:
  - project: 'DRS/linux-packages/shared-ci-pipeline'
    file: '.upload_rhel-gitlab-ci.yml'
  - project: 'DRS/linux-packages/templated-python-venv/shared-pipelines'
    file: '.el-venv-gitlab-ci.yml'

variables:
  PKG_NAME: liuopt-cccollector
  # Set manually each run: PKG_PROG_VER

ccc-rhel-opt-package:
  stage: package
  image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel9:latest'
  rules:
    - if: $PK_PROG_VER
    - when: manual
  variables:
    INSTALL_PATH: /opt/liu
    PKG_PREFIX: liuopt
    PKG_VERSION: $PKG_PROG_VER
  artifacts:
    paths:
      - pkgs
  script:
    - dnf update
    - rpmbuild collector.spec
    - mkdir -p pkgs/rhel9
    - mv rpms/noarch/*.rpm pkgs/rhel9

pywb-rhel-opt-package:
  extends: .el-venv-opt-package
  stage: package
  when: manual
  variables:
    PKG_NAME: 'liuopt-ccc-pywb-venv'
    PKG_PROG_VER: '1-1'
    PKG_PREFIX: 'liuopt'
    PKG_INSTALLPATH: 'opt/liu'
    PKG_VERSION: '1'
    PKG_RELEASE: '1'
    build_image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel9:latest'
    target_distro: rhel9

collect-pkgs:
  stage: collect
  when: manual
  artifacts:
    untracked: true
  dependencies:
    - ccc-rhel-opt-package
    - pywb-rhel-opt-package
  script:
    - "mv pkgs/* ."
    - "find . | grep .rpm"

upload-pkgs:
  extends: .upload-el-pkgs
  dependencies:
    - collect-pkgs
  variables:
    target_dir: rhel9
    upload_script: './upload-Plow-test.sh'
