stages:
  - package
  - collect
  - upload

include:
  - project: 'DRS/linux-packages/shared-ci-pipeline'
    file: '.upload_rhel-gitlab-ci.yml'
  - project: 'DRS/linux-packages/templated-python-venv/shared-pipelines'
    file: '.el-venv-gitlab-ci.yml'

variables:
  PKG_PREFIX: 'liuopt'
  PKG_VERSION: '1'
  PKG_RELEASE: '1'

ccc-rhel-opt-package:
  stage: package
  when: manual
  image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel8:latest'
  variables:
    PKG_NAME: 'liuopt-cccollector'
    PKG_INSTALLPATH: '/opt/liu'
    PKG_PROG_VER: '1'
    PKG_SUMMARY: 'Common Crawl Collector'
    PKG_LICENSE: 'GPLv3'
  artifacts:
    paths:
      - pkgs
  script:
    - dnf update
    - rpmbuild --define "_rpmdir $(pwd)/rpms" collector.spec
    - mkdir -p pkgs/rhel${dist_ver}
    - ls rpms
    - mv rpms/noarch/*.rpm pkgs/rhel8
    #           ^ Elsewhere?

pywb-rhel-opt-package:
  extends: .el-venv-opt-package
  when: manual
  variables:
    PKG_NAME: 'liuopt-ccc-pywb-venv'
    PKG_INSTALLPATH: 'opt/liu'
    PKG_PROG_VER: '1-1'
    target_distro: rhel8
    build_image: 'gitlab.it.liu.se:5000/serverdrift-projs/ci/packaging-images/base/rhel8:latest'

collect-pkgs:
  stage: collect
  when: manual
  artifacts:
    untracked: true
  script:
    - "mv pkgs/* ."
    - "find . | grep .rpm"

upload-rhel-pkgs:
  extends: .upload-el-pkgs
  dependencies:
    - collect-pkgs
  variables:
    target_dir: rhel8
    upload_script: './upload-Ootpa-test.sh'
