{
 "title": "CC Collector",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(up{job=\"common_crawl_collectors\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "collector_status_info{hostname=\"$host\"}"
    }
   ]
  },
  {
   "title": "Collector State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "collector_state{collector_state=\"collecting\", hostname=\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Retry Queue Items",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collector_retryqueue{hostname=\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(collector_requests_total{hostname=\"$host\"}[1m])",
     "legendFormat": "Sent/m"
    },
    {
     "expr": "delta(collector_failed_total{hostname=\"$host\"}[1m])",
     "legendFormat": "Failed/m"
    }
   ]
  },
  {
   "title": "Failed Requests Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "$B>0 && ($A/$B)*100*($A>0) || 0",
     "type": "math"
    }
   ]
  },
  {
   "title": "Downstream (Approximated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(collector_download_size_sum{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}